// Concatenates src/*.js into a single classic (non-module) script at
// dist/gp-treemap.bundle.js so HTML can load it with `<script src>` under
// file:// — no server, no module CORS, works anywhere.
//
// Strategy is zero-dep, naïve, and deliberate:
//   * Strip `import ...` lines entirely.
//   * Strip `export {...}` lines entirely.
//   * Rewrite `export function|class|const|let|var X` to `function|class|const|let|var X`.
//   * Concatenate in dependency order and wrap the whole thing in one IIFE so
//     declarations share a scope.
//   * customElements.define runs at the bottom of gp-treemap.js, so loading
//     the bundle registers the element.

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const ORDER = [
  'hash.js',
  'palettes.js',
  'color-scale.js',
  'color-resolver.js',
  'balancer.js',
  'layout.js',
  'builder.js',
  'lut.js',
  'painter.js',
  'format.js',
  'gp-treemap.js',
];

function strip(src) {
  let out = src.replace(/^\s*import\s+[^;]+;\s*$/gm, '');
  out = out.replace(/^\s*export\s+(function|class|const|let|var)\s+/gm, '$1 ');
  out = out.replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '');
  return out;
}

const parts = [
  '/* gp-treemap — single-file build (generated by tools/build.js) */',
  '(function(){ "use strict";',
];
for (const name of ORDER) {
  const code = fs.readFileSync(path.join(SRC, name), 'utf8');
  parts.push(`/* ---- src/${name} ---- */`);
  parts.push(strip(code));
}
// Expose a handful of symbols for the unit-fixture tests.
parts.push('try { if (typeof window !== "undefined") window.GpTreemap = { GpTreemap, fnv1a, balanceChildren, maxDepth, layoutTree, buildFromTabular, buildFromTree, buildLinearScale, buildLogScale, buildDivergingScale, buildQuantileScale, autoDomain, resolveColors, paintCell, paintAll, buildLUTs }; } catch (e) {}');
parts.push('})();');

fs.mkdirSync(DIST, { recursive: true });
const outPath = path.join(DIST, 'gp-treemap.bundle.js');
const bundleSrc = parts.join('\n');
fs.writeFileSync(outPath, bundleSrc);
console.log('wrote ' + path.relative(ROOT, outPath) + ' (' + fs.statSync(outPath).size + ' bytes)');

// Also emit an ESM module that re-exports the bundle source as a string,
// so tools (gpdu-scan.js) can `import` it instead of fs.readFileSync — that
// way Deno's module loader handles the read and no --allow-read is needed
// on the npm cache directory.
const embedPath = path.join(DIST, 'gp-treemap.bundle.embed.js');
const escaped = bundleSrc.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
fs.writeFileSync(embedPath, 'export const BUNDLE = `' + escaped + '`;\n');
console.log('wrote ' + path.relative(ROOT, embedPath) + ' (' + fs.statSync(embedPath).size + ' bytes)');

// Emit dist/scan-loader.embed.js — the browser-side IIFE shared across the
// gpdu-* CLI family. Source lives in tools/scan-loader.source.js; we read
// it here and re-export as a string constant so each gpdu-* tool can import
// LOADER_JS without doing fs.readFileSync (which would need --allow-read on
// the npm cache directory under Deno).
const loaderSrc = fs.readFileSync(path.join(ROOT, 'tools', 'scan-loader.source.js'), 'utf8');
const loaderEscaped = loaderSrc.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const loaderEmbedPath = path.join(DIST, 'scan-loader.embed.js');
fs.writeFileSync(loaderEmbedPath, 'export const LOADER_JS = `' + loaderEscaped + '`;\n');
console.log('wrote ' + path.relative(ROOT, loaderEmbedPath) + ' (' + fs.statSync(loaderEmbedPath).size + ' bytes)');
