// Concatenates src/*.js into a single classic (non-module) script at
// dist/gp-treemap.bundle.js so HTML can load it with `<script src>` under
// file:// — no server, no module CORS, works anywhere.
//
// Strategy is zero-dep, naïve, and deliberate:
//   * Strip `import ...` lines entirely.
//   * Strip `export {...}` lines entirely.
//   * Rewrite `export function|class|const|let|var X` to `function|class|const|let|var X`.
//   * Concatenate in dependency order and wrap the whole thing in one IIFE so
//     declarations share a scope.
//   * customElements.define runs at the bottom of gp-treemap.js, so loading
//     the bundle registers the element.

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const ORDER = [
  'hash.js',
  'palettes.js',
  'color-scale.js',
  'color-resolver.js',
  'balancer.js',
  'layout.js',
  'builder.js',
  'lut.js',
  'painter.js',
  'format.js',
  'gp-treemap.js',
];

function strip(src) {
  let out = src.replace(/^\s*import\s+[^;]+;\s*$/gm, '');
  out = out.replace(/^\s*export\s+(function|class|const|let|var)\s+/gm, '$1 ');
  out = out.replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '');
  return out;
}

const parts = [
  '/* gp-treemap — single-file build (generated by tools/build.js) */',
  '(function(){ "use strict";',
];
for (const name of ORDER) {
  const code = fs.readFileSync(path.join(SRC, name), 'utf8');
  parts.push(`/* ---- src/${name} ---- */`);
  parts.push(strip(code));
}
// Expose a handful of symbols for the unit-fixture tests.
parts.push('try { if (typeof window !== "undefined") window.GpTreemap = { GpTreemap, fnv1a, balanceChildren, maxDepth, layoutTree, buildFromTabular, buildFromTree, buildLinearScale, buildLogScale, buildDivergingScale, buildQuantileScale, autoDomain, resolveColors, paintCell, paintAll, buildLUTs }; } catch (e) {}');
parts.push('})();');

fs.mkdirSync(DIST, { recursive: true });
const outPath = path.join(DIST, 'gp-treemap.bundle.js');
fs.writeFileSync(outPath, parts.join('\n'));
console.log('wrote ' + path.relative(ROOT, outPath) + ' (' + fs.statSync(outPath).size + ' bytes)');
